version: '3'

services:
  backend:
    build: ./backend/
    restart: always
    ports:
      - 80:80

  frontend:
    image: node:20
    restart: always
    working_dir: /srv/app/
    ports:
      - 8080:8080
    volumes:
      - ./frontend/:/srv/app/
    command: sh -c "npm install && npm run dev"
